version: "3"

networks:
  drone_gitea:
    external: false

services:
  #   drone-service:
  #     image: drone/drone:2
  #     container_name: drone-service
  #     environment:
  #       DRONE_GITEA_SERVER:
  #       DRONE_GITEA_CLIENT_ID: b6e91382-1b36-4fce-8be6-c5a8e32249b0
  #       DRONE_GITEA_CLIENT_SECRET: gto_yopuqaxk3o7kmyi7rldloargn4vkxzrvnawvg3lcx7orlzfnvxia
  #       DRONE_RPC_SECRET: 66e2628f3acad269b7528956ffbf6e2b
  #       DRONE_SERVER_HOST: localhost:7000
  #       DRONE_SERVER_PROTO: http
  #     restart: always
  #     volumes:
  #       - ./drone:/data
  #     ports:
  #       - "7000:80"
  #     networks:
  #       - drone_gitea

  # drone-runner-service:
  #   image: drone/drone-runner-docker:1.8.3
  #   container_name: drone-runner-service
  #   environment:
  #     DRONE_RPC_PROTO: http
  #     DRONE_RPC_HOST: localhost:7000
  #     DRONE_RPC_SECRET: 66e2628f3acad269b7528956ffbf6e2b
  #     DRONE_RUNNER_CAPACITY:  2
  #     DRONE_RUNNER_NAME: my-runner
  #   restart: always
  #   volumes:
  #     - /run/user/1000/podman/podman.sock:/var/run/docker.sock
  #   networks:
  #     - drone_gitea
  #   depends_on:
  #     - drone-service

  gitea-service:
    image: gitea/gitea:1.18.0
    container_name: gitea-service
    environment:
      USER_UID: 1000
      USER_GID: 1000
      # GITEA__server__HTTP_PORT: "3001"
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    restart: always
    networks:
      - drone_gitea
    volumes:
      - ./gitea:/data:rw
    ports:
      - "3001:3001"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    networks:
      - drone_gitea
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
